spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartcity_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver   # ← 드라이버 클래스 명시

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect   # ← 방언 추가

server:
  port: 8080

external:
  fastapi:
    url: http://fastapi:8001/chat

recaptcha:
  secret: 6Ld1lmArAAAAAGvarEbptb3-i1gnutfvF3L2w0ub

kakao:
  rest-api-key: 8413a4aab24c3a25cc81eb161bcd7277

